### ISSUE TITLE
screenshot to update

### ISSUE THREAD

**Issue by MalikaIhle** [MalikaIhle/collaborative_github_exercise#253]
can you have 
![image](https://github.com/lmu-osc/Collaborative-RStudio-GitHub/assets/16382829/1423f039-4649-453a-b2c7-6645ba4f5b72)
at the bottom of the fork page to replcae the last screen shot?

**Comment by MalikaIhle** [comment]
replace 
![image](https://github.com/lmu-osc/Collaborative-RStudio-GitHub/assets/16382829/2d7c478d-11f6-4686-9192-df9530c28786)
on the git push page

**Comment by MalikaIhle** [comment]
this screen shot is wrong
![image](https://github.com/lmu-osc/Collaborative-RStudio-GitHub/assets/16382829/738fb230-5196-465f-b874-1cba636ecb0f)
I think this represent the result of the merge - but with your (Adam Kenny's here)  own paramter species not malika rocks and it should be a merge to the LMU OSC not Malika's repo 


maybe we should just delete that screenshot otherwise you'd need to redo everything...

**Comment by MalikaIhle** [comment]
these screenshots in pull upstream page are wrong
![image](https://github.com/lmu-osc/Collaborative-RStudio-GitHub/assets/16382829/39d755d5-11ca-4d9a-8dc3-d5ce36a17cc4)

**Comment by MalikaIhle** [comment]
Hi Martin - there are some revisions to make on the screen shots - can you do this?

**Comment by MWiehr** [comment]
yes I´ll work on it after my lectures today

**Comment by MWiehr** [comment]
> can you have ![image](https://private-user-images.githubusercontent.com/16382829/334031228-1423f039-4649-453a-b2c7-6645ba4f5b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTcxNzgsIm5iZiI6MTcxNjgxNjg3OCwicGF0aCI6Ii8xNjM4MjgyOS8zMzQwMzEyMjgtMTQyM2YwMzktNDY0OS00NTNhLWIyYzctNjY0NWJhNGY1YjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2VkOWQxMGViMzQwNDA1NmQ4YjdkM2M4MDY3YjBmOWFhZjA5ZmVlOGQ2NjBkNDAxYmUwN2E2Mjk3MmIwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5yvamWmdXIVDOWAlpLI752vtum3HmH4gx-0YE4QSryo) at the bottom of the fork page to replcae the last screen shot?

 I just deleted my fork to fork again and I didn´t get a screen that said forking - it should only take a few seconds. This is the closest one that I was able to get.
![issue_1_forking](https://github.com/lmu-osc/Collaborative-RStudio-GitHub/assets/122365830/3856030a-53fa-4b00-9710-ef23dcb35ea0)

**Comment by MWiehr** [comment]
> these screenshots in pull upstream page are wrong ![image](https://private-user-images.githubusercontent.com/16382829/334035661-39d755d5-11ca-4d9a-8dc3-d5ce36a17cc4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MjU3MzUsIm5iZiI6MTcxNjgyNTQzNSwicGF0aCI6Ii8xNjM4MjgyOS8zMzQwMzU2NjEtMzlkNzU1ZDUtMTFjYS00ZDlhLThkYzMtZDVjZTM2YTE3Y2M0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDE1NTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwY2FmZTQ2ZjA3NzFhNmRjMzc2MWZiZDQyZmY5ODQwMzJhOTRmMzc5NTE0YTM3ZDM1YTBkNzc4YzkwMTZhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e43GKK43Du3oFIqK92W7oBorID_D-yXEe_vThzjRijo)

I´m not 100% clear if I understood the problem entirely. Is the problem that it also refers to the wrong repo or is it to do with the interface? I intuitively used the R terminal -> let me know if that is ok
![pull_from_upstream](https://github.com/lmu-osc/Collaborative-RStudio-GitHub/assets/122365830/fb4bc2c5-5ea1-4d3f-8ad4-a3afc018039c)

**Comment by MalikaIhle** [comment]
> > can you have ![image](https://private-user-images.githubusercontent.com/16382829/334031228-1423f039-4649-453a-b2c7-6645ba4f5b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTcxNzgsIm5iZiI6MTcxNjgxNjg3OCwicGF0aCI6Ii8xNjM4MjgyOS8zMzQwMzEyMjgtMTQyM2YwMzktNDY0OS00NTNhLWIyYzctNjY0NWJhNGY1YjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2VkOWQxMGViMzQwNDA1NmQ4YjdkM2M4MDY3YjBmOWFhZjA5ZmVlOGQ2NjBkNDAxYmUwN2E2Mjk3MmIwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5yvamWmdXIVDOWAlpLI752vtum3HmH4gx-0YE4QSryo) at the bottom of the fork page to replcae the last screen shot?
> 
> I just deleted my fork to fork again and I didn´t get a screen that said forking - it should only take a few seconds. This is the closest one that I was able to get. ![issue_1_forking](https://private-user-images.githubusercontent.com/122365830/334121726-3856030a-53fa-4b00-9710-ef23dcb35ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODczNjEsIm5iZiI6MTcxNjg4NzA2MSwicGF0aCI6Ii8xMjIzNjU4MzAvMzM0MTIxNzI2LTM4NTYwMzBhLTUzZmEtNGIwMC05NzEwLWVmMjNkY2IzNWVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwOTA0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGQ5ZTUyN2IyOWI1ZTg1ZjRlYTUzZmE0MGE0MDIyNzYxZGM1NjQzZTczMzhjYzk2ODEwZTg1Mzk4NmQ4MDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._W3aAorcVIsd0iVixn3q5ii3dQb0tM89YAx3WKFdQVI)

it doesn't do the image of a book scanned with a fork on top?

**Comment by MWiehr** [comment]
> > > can you have ![image](https://private-user-images.githubusercontent.com/16382829/334031228-1423f039-4649-453a-b2c7-6645ba4f5b72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4MTcxNzgsIm5iZiI6MTcxNjgxNjg3OCwicGF0aCI6Ii8xNjM4MjgyOS8zMzQwMzEyMjgtMTQyM2YwMzktNDY0OS00NTNhLWIyYzctNjY0NWJhNGY1YjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI3VDEzMzQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwM2VkOWQxMGViMzQwNDA1NmQ4YjdkM2M4MDY3YjBmOWFhZjA5ZmVlOGQ2NjBkNDAxYmUwN2E2Mjk3MmIwMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5yvamWmdXIVDOWAlpLI752vtum3HmH4gx-0YE4QSryo) at the bottom of the fork page to replcae the last screen shot?
> > 
> > 
> > I just deleted my fork to fork again and I didn´t get a screen that said forking - it should only take a few seconds. This is the closest one that I was able to get. ![issue_1_forking](https://private-user-images.githubusercontent.com/122365830/334121726-3856030a-53fa-4b00-9710-ef23dcb35ea0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4ODczNjEsIm5iZiI6MTcxNjg4NzA2MSwicGF0aCI6Ii8xMjIzNjU4MzAvMzM0MTIxNzI2LTM4NTYwMzBhLTUzZmEtNGIwMC05NzEwLWVmMjNkY2IzNWVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyOFQwOTA0MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OGQ5ZTUyN2IyOWI1ZTg1ZjRlYTUzZmE0MGE0MDIyNzYxZGM1NjQzZTczMzhjYzk2ODEwZTg1Mzk4NmQ4MDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9._W3aAorcVIsd0iVixn3q5ii3dQb0tM89YAx3WKFdQVI)
> 
> it doesn't do the image of a book scanned with a fork on top?

At least it didnt after deleting the fork and then forking again. I can try forking another repo to see if it has to do with forking a repo for the first time
